# Generated by Django 3.1.3 on 2020-11-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dept_name',
        ),
    ]
